# Generated by Django 3.2.9 on 2021-11-28 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TRANSACTION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(max_length=256)),
                ('card_number', models.PositiveBigIntegerField(default=1000100010001000, validators=[django.core.validators.MinValueValidator(1000000000000000), django.core.validators.MaxValueValidator(9999999999999999)])),
                ('month', models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], default='JANUARY', max_length=9)),
                ('year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(2021), django.core.validators.MaxValueValidator(2030)])),
                ('CVC', models.PositiveIntegerField(default=111, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(9999)])),
                ('payment_date', models.DateField()),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
